<?php

namespace CCETC\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationInstanceRepository extends EntityRepository
{

}